###############################################################################
## definition des couleurs et des fontes pour les display
###############################################################################
# changelogs:
# V2.0 ajout des fontes pour lcd Cuisine
# V1.0 colors + fonts
####################
##lilygo S3
####################

color:
  - id: night_red
    red: 100%
    green: 3%
    blue: 5%
    
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
    
  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%
    
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
    
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%
    
  - id: my_grey
    red: 50%
    green: 50%
    blue: 50%
    
  - id: my_white
    red: 100%
    green: 100%
    blue: 100%
    
  - id: color_light_grey
    hex: BBBBBB   
    
  - id: color_dark_grey
    hex: 5F5F5F
    
  - id: color_white
    hex: FFFFFF
    
  - id: color_red
    hex: FF0000
    
  - id: color_green
    hex: 00FF00
    
  - id: color_yellow
    hex: FFFF00    
    
    
    
# Set fonts
font:
  - file: "fonts/boldfont.ttf"
    id: verysm_boldfont
    size: 15
  - file: "fonts/boldfont.ttf"
    id: small_boldfont
    size: 25
  - file: "fonts/boldfont.ttf"
    id: med1_boldfont
    size: 35    
  - file: "fonts/boldfont.ttf"
    id: med_boldfont
    size: 40
  - file: "fonts/boldfont.ttf"
    id: big_boldfont
    size: 60
  - file: "fonts/boldfont.ttf"
    id: vbig_boldfont
    size: 80
    
  - file: "gfonts://Roboto"
    id: ipfont
    size: 15
  - file: "gfonts://Roboto"
    id: up_barfont
    size: 25
  - file: "gfonts://Roboto"
    id: big_clockfont
    size: 60
  - file: "gfonts://Roboto"
    id: font_temp
    size: 28
    
  - file: "fonts/Helvetica.ttf"
    id: helvetica_48
    size: 48
  - file: "fonts/Helvetica.ttf"
    id: helvetica_24
    size: 24
  - file: "fonts/Helvetica.ttf"
    id: helvetica_12
    size: 12    

## LCD Cuisine

  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_mdi_large
    size: 200
    glyphs: &mdi-weather-glyphs
      - "\U000F0590" # mdi-weather-cloudy
      - "\U000F0F2F" # mdi-weather-cloudy-alert
      - "\U000F0E6E" # mdi-weather-cloudy-arrow-right
      - "\U000F0591" # mdi-weather-fog
      - "\U000F0592" # mdi-weather-hail
      - "\U000F0F30" # mdi-weather-hazy
      - "\U000F0898" # mdi-weather-hurricane
      - "\U000F0593" # mdi-weather-lightning
      - "\U000F067E" # mdi-weather-lightning-rainy
      - "\U000F0594" # mdi-weather-clear-night
      - "\U000F0F31" # mdi-weather-night-partly-cloudy
      - "\U000F0595" # mdi-weather-partly-cloudy
      - "\U000F0F32" # mdi-weather-partly-lightning
      - "\U000F0F33" # mdi-weather-partly-rainy
      - "\U000F0F34" # mdi-weather-partly-snowy
      - "\U000F0F35" # mdi-weather-partly-snowy-rainy
      - "\U000F0596" # mdi-weather-pouring
      - "\U000F0597" # mdi-weather-rainy
      - "\U000F0598" # mdi-weather-snowy
      - "\U000F0F36" # mdi-weather-snowy-heavy
      - "\U000F067F" # mdi-weather-snowy-rainy
      - "\U000F0599" # mdi-weather-sunny
      - "\U000F0F37" # mdi-weather-sunny-alert
      - "\U000F14E4" # mdi-weather-sunny-off
      - "\U000F059A" # mdi-weather-sunset
      - "\U000F059B" # mdi-weather-sunset-down
      - "\U000F059C" # mdi-weather-sunset-up
      - "\U000F0F38" # mdi-weather-tornado
      - "\U000F059D" # mdi-weather-windy
      - "\U000F059E" # mdi-weather-windy-variant
      - "\U000F10AF" # mdi-door-closed-lock
      - "\U000F081C" # mdi-door-open
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_mdi_medium
    size: 40
    glyphs: *mdi-weather-glyphs     